### ISSUE TITLE
kernel: Module Items are initialized on every boot

### ISSUE THREAD

**Issue by abranson** [cristal-ise/cristal-ise#104]
This generates an ItemInitialization Event and Outcome every time the server is started.

**Comment by kovax** [comment]
Load ImportItem resource Items from independent file in boot/item directory during bootstrap. This way bootstrap can make the diff the xml files and only update the Item if needed. In other words, the declaration of Items are removed from the module.xml.

- [ ] Load ImportItem resource Item instances from independent file in boot/item directory
- [ ] Add reference link in the module.xml to load the new resource Item from the files
