### ISSUE TITLE
dsl: add 'pattern' to dynamicForms section to support front-end validation 

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#119]
The DSL allows us to specify a validation pattern for a field in an outcome. This pattern is used both on the back-end to perform XML validation and on the front-end to perform input validation. But the back-end pattern should be in XSD regex format, while the front-end pattern should be in JavaScript format.

We will have to have two separate validation patterns: one for front-end and one for back-end.
For the front-end pattern we should also allow the schema to specify a user-friendly validation message.

XSD pattern validation:
- [XML Schema Regular Expressions](https://msdn.microsoft.com/en-us/library/ms256481(v=vs.110).aspx)
- [XML Schema Regular Expressions](https://www.regular-expressions.info/xml.html)

HTML5 pattern validation:
- [HTML Living Standard - The pattern attribute](https://html.spec.whatwg.org/multipage/input.html#the-pattern-attribute)
- [JavaScript Regular Expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)
- https://developer.mozilla.org/en-US/docs/Web/API/Constraint_validation#Constraint_validation_interfaces
- https://webdesign.tutsplus.com/tutorials/html5-form-validation-with-the-pattern-attribute--cms-25145

**Comment by kovax** [comment]
- [ ] add `pattern` to dynamicForms section to support front-end validation
- [ ] While generating the ngDynamicForms json use the `pattern` in dynamicForms as validator instead of the pattern specified for XSD
