### ISSUE TITLE
ListOfValues populated from values should not be editable by default

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#131]
If a field is declared with 
```
listOfValues(values: deviceTypes)
```
instead of
```
values: deviceTypes
```
then the user will be able to enter any arbitrary value in the field, because by default it is set to editable in the `populateLOVFromValues()` method:
https://github.com/cristal-ise/cristal-ise/blob/8c359dd0d4b9631cf50690e85df4411dcb264129/xpath-outcome-initiator/src/main/java/org/cristalise/kernel/persistency/outcomebuilder/field/ListOfValues.java#L237

We should remove this line, but only after making sure that we can specify the additional setting `editable: true` in the DSL and apply that change to all existing groovy dsl files that have `values:` set.

Note: this is not a problem with `listOfValues(scriptRef:`

**Comment by kovax** [comment]
This is covered in #132

**Comment by taurus227** [comment]
According to @kovax it is covered in #132 because the default can now be overridden by `editable: false`: https://github.com/cristal-ise/cristal-ise/pull/260/files#diff-35a632c7d3978b45774df2648a739dc8R10
