### ISSUE TITLE
Password change: temporaryPassword flag stays true until the REST server is restarted

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#143]
If a user has a temporary password, when they log in, they are forced to change it.
This works, but on their next login they will be asked to change password again.
The problem is the `temporaryPassword` flag stays `true` until the REST server is restarted.

```
{
    "Login": {
        "result": "Success",
        "temporaryPassword": "true"
    }
}
```

**Comment by kovax** [comment]
This is a caching issue. The AgentProxy is cached and the subsequent login will find it.

**Comment by taurus227** [comment]
There's no way to invalidate the Proxy cache. Instead of the AgentProxy, we will read the "temporary" flag from the Lookup, because the Lookup is not cached.
