### ISSUE TITLE
User still logged in after browser restart

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#162]
If the user closes the browser and re-opens it, the login window is shown with the menu still displayed, but no need to log in, the user can do actions!

**Comment by taurus227** [comment]
This is because the cookie is not deleted upon exit from the browser.
In 
https://github.com/cristal-ise/cristal-ise/blob/31300b95ac8ca779eda98096314a394ce17db0af/restapi/src/main/java/org/cristalise/restapi/CookieLogin.java#L96
the `maxAge` parameter of `NewCookie` is set.
If it was not set, it would be considered a session cookie and would be cleared on browser exit.
We should not set it and should track the cookie expiration on the server side! The server should know if a cookie is valid or not, without relying on the browser, otherwise it becomes a security issue.

**Comment by kovax** [comment]
The can evaluate the cookie, it encodes agent uuid and expiration timestamp. Check class AuthData:

    public class AuthData {
        AgentPath agent;
        Date timestamp;
    }
