### ISSUE TITLE
Permissions set to a role are being erased after logging in.

### ISSUE THREAD

**Issue by rburawes** [cristal-ise/cristal-ise#179]
1. log-in as user admin user.
2. import roles (application specific)
3. Enable and edit role and give write permission to all item activities
4. Save the role editing and log-out <----- Here it actually saves the permissions
5. Login as a user with permission to item activities  **<----- Here after the login the permissions have been erased by Cristal.**
6. Go to item page and click on "New": an error appears and it is not possible to create a new item **<----- So, here it will fail since the permission is gone.**

**Comment by kovax** [comment]
This issue cannot be reproduced
