### ISSUE TITLE
[restapi] XML 2 JSON conversion of unit attribute

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#188]
When generating the JSON from the XML, make sure the unit attribute of a field is converted to a fieldName_Unit in the JSON and it's converted back properly.

**Comment by taurus227** [comment]
This might not be needed, the field is converted into a struct:
Weight: {content: "25", unit: "kg"}

**Comment by kovax** [comment]
JSON to XML conversion is done by the josn.org library, and currently it not possible to configure it.
