### ISSUE TITLE
NgDynamicForms: Support the hideOnDateTimeSelect setting for dateTime fields

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#212]
In addition to the change made in #175, also support the `hideOnDateTimeSelect` setting for dateTime fields

**Comment by kovax** [comment]
Could you explain what it does, just for future reference, and I can as javadoc as well.

**Comment by taurus227** [comment]
On this page: https://www.primefaces.org/primeng/#/calendar see `hideOnDateTimeSelect` under **Properties**.
When a calendar is shown for a **date** field, clicking on a day makes the calendar drop-down disappear. But when a calendar is shown for a **dateTime** field (`showTime is set to `true`), clicking on a date will not make the drop-down disappear by default. This option changes the default behavior, thereby making **dateTime** fields work the same as **date** fields.
