### ISSUE TITLE
Remove JooqDB dependency from restapi

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#22]
Pull request #55 Introduced a dependency to jooqdb, see
https://github.com/cristal-ise/restapi/pull/55/files#diff-600376dffeb79835ede4a0b285078036R259

It is used in this line:
https://github.com/cristal-ise/restapi/pull/55/files#diff-72bfef9f2a8704a31b10ed08071f3c5aR104

Refactor the code by making the following changes:
- [ ] 1. Move the initialisation of the jooq connection from ScriptAccess to ScriptUtils
- [ ] 2. Implement Dependency Injection for the ScriptUtils class, so that it can be replaced by another implementation  
- [ ] 3. Implement a descendant of ScriptUtils in the Titus platform (or the project), which depends on jooqdb and overrides `executeScript`, then inject it to be used
- [ ] 4. Move the initialization of the jooq connection from ScriptUtils into the new descendant
- [ ] 5. Change back the jooqdb dependency from `compile` to `test`

**Comment by taurus227** [comment]
See also https://github.com/cristal-ise/cristal-ise/issues/43

**Comment by kovax** [comment]
This will not be implemented, because the restapi shall not execute script with write transaion. In fact if shall be configured to run in read-only transaction mode
