### ISSUE TITLE
Move docs to readthedocs.org

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#244]
Move cristal docs from GitHub Wiki to https://docs.readthedocs.io/en/stable/index.html
Here's an example of how to move it, although it seems here the docs were in ReStructured Text format, not MarkDown: https://github.com/ISA-tools/isa-api/issues/102

**Comment by samottitusgt** [comment]
Done moving all documentation to https://cristal-ise.readthedocs.io. Need fixing some broken links.
