### ISSUE TITLE
Security Padding Issue

### ISSUE THREAD

**Issue by genetorres** [cristal-ise/cristal-ise#267]
Error logged in REST API: 

```
ERROR  : Exception caught in decryptAuthData: #1: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
ERROR  : Exception caught in decryptAuthData: #2: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
ERROR  : Exception caught in decryptAuthData: #3: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
ERROR  : Exception caught in decryptAuthData: #4: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
ERROR  : Exception caught in decryptAuthData: #5: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
ERROR  : Given final block not properly padded. Such issues can arise if a bad key is used during decryption. - 
authData:HNDnXMuqgJU05ShPxylmBjrbeyM3lw3AhM5v1jed+MLByBEY3F/eiSJVh/1SJNudzusodaGhIZWbXipCm4vAwilgtXKPrOVTqoQRLsJGKr7ByVIx0PrzTeAjl/RkMfGw8OaNMdCXVfTP+VGW4mvIaTy6SYOP5IG0zm09s13Fe0qfLCd/Fu7cXMREdmFO3d2Y7fyhhuKyhqtRp+aVp3deJ4n6HUhHeaL/6j8654TF8kBzDbMxIaVPyO6IOe4D30m6mJmp4Zpm2gFM8KtVhXDGlA==
```

The code retries 5 times, because usually in 1 or 2 retries it passes. WITH THE SAME INPUT DATA!

It seems this can happen when there are multiple Security Providers and a different one is used in a different thread for decoding than the one that was used for encoding. Solution is to choose one explicitly. For more details see https://stackoverflow.com/a/5100805/2969332

**Comment by kovax** [comment]
Each rest call is a separate thread, and the Chipper class is not threadsafe:
https://stackoverflow.com/questions/6957406/is-cipher-thread-safe

This means that the chipper instances should be stored in ThreadLocal variable instead of in a static field:
https://stackoverflow.com/questions/11942466/create-and-maintain-multiple-ciphers

**Comment by kovax** [comment]
We should use Shiro CipherService instead o of hand-written code:
- https://shiro.apache.org/static/1.4.0/apidocs/org/apache/shiro/crypto/CipherService.html
- https://stackoverflow.com/questions/31365132/apache-shiro-aes-encryption-differs-from-expected-output
