### ISSUE TITLE
DSL: Ability to override resourcesRoot, exportRoot and moduleDir paths

### ISSUE THREAD

**Issue by rburawes** [cristal-ise/cristal-ise#295]
The current implementation from the ModuleDelegate constructor prevents the passed directory values for `resourcesRoot`, `exportRoot` and `moduleDir` to be used in creating the `Module`.  The constructor is being called first before setting the properties.

```
    public ModuleDelegate(String ns, String n, int v, String resRoot, String expRoot, String modDir, Binding b = null) {
        this(ns, n, v, b)

        if (resRoot) resourceRoot = resRoot
        if (expRoot) exportRoot   = expRoot
        if (modDir)  moduleDir    = modDir

        resourceBoot = "$resourceRoot/boot"
        moduleXMLFile = new File("$resourceRoot/module.xml")
    }
```

**Comment by kovax** [comment]
This is already supported.

Module.groovy it is possible to set the resourceRoot, see code bellow and test file `dsl/test/module/Module.groovy`

```groovy
setResourceRoot 'src/test/resources'

Module(ns: 'testns', name: 'DSL Test', version: 0) {
....
}
