### ISSUE TITLE
Revert commit id: 66b9df9

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#301]
This change needs to be reverted: https://github.com/cristal-ise/cristal-ise/commit/66b9df93dbdc7bbc02a17dd24734a33e4ddfc4d0
It was done for #213 which is based on [AAAT-3224](https://icube-sa.atlassian.net/browse/AAAT-3224)

Unfortunately the side effect of this change is that the converter tries to interpret numbers even when it shouldn't.
For example:
- a document ID of the form "002345" will be converted to "2345" because it's interpreted as a number
- a storage location code of the form "14E2" will be converted to "1400" because it's interpreted as a number in scientific format

The best solution seems to be to revert the change, interpret everything as string and do the conversion (if necessary, like for a boolean value) on the front-end.

**This change might cause regressions so we need to make sure everything still works!**

**Comment by taurus227** [comment]
While I think this is the best way to go about it, doing this change will cause regressions which need to be fixed.
There is no urgency to implementing this fix, we have found a workaround for our special case.

**Comment by kovax** [comment]
Shall be overed in #306
