### ISSUE TITLE
Attachment endpoint does not return the binary file

### ISSUE THREAD

**Issue by hyperion21** [cristal-ise/cristal-ise#323]
Currently `/attachment/{schema_name}/{version}/{event_id}` returns an outcome. Change it to file attached based from the binary data from outcome attachment

**Comment by kovax** [comment]
Also, the MIME type is not saved with the attachment.

The ATTACHMENT table is extended with MIME_TYPE column, therefore the table has to be migrated for existing applications. It is possible to switch off that functionality by setting the following system property:

`JOOQ.OutcomeAttachment.enableMimeType = false`
