### ISSUE TITLE
Implement requestBinaryTransition() restapi endpoint to store Outcome with binary attachment

### ISSUE THREAD

**Issue by hyperion21** [cristal-ise/cristal-ise#325]
`accept` property is optional by default in `dynamic form input` field. We can use `accept` to determine valid file types for `dynamic form input` with `inputType='file'`. And it can be separated by commas(,)

**Comment by kovax** [comment]
@hyperion21 Could you rename this field to be more precise? How about acceptedMimeTypes? Can you also add a comment explaining the purpose?

**Comment by hyperion21** [comment]
@kovax `accept` is a field in dynamicForms. It is used especially in `input` with type `file` to determine the accepted file types

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
