### ISSUE TITLE
The log "itemPath is null!" during bootstrap could be avoided for StateMachine, Schema, Query and Script

### ISSUE THREAD

**Issue by martinbielmannicube** [cristal-ise/cristal-ise#333]
When running Module, the following logs are generated for items StateMachine, Schema, Query and Script: 

`06:57:10.323 [Bootstrapper] WARN  o.c.kernel.lifecycle.ActivityDef - getBuiltInCollectionResource(actName:Report_Workflow, collection:Activity) - itemPath is null! CANNOT resolve data in ClusterStorage`

According to @kovax this is due to a bug.

**Comment by kovax** [comment]
This log is indicates that bootstrap resource importing methods are called for none existing built-in collections of ActivityDef.

**Comment by kovax** [comment]
The log was changed to DEBUG level
