### ISSUE TITLE
Add UUID field type

### ISSUE THREAD

**Issue by khoeraine28** [cristal-ise/cristal-ise#340]
Add support for UUID field type in Schema

**Comment by kovax** [comment]
Do you need this to know if the field is referencing an Item?

This is support already using Reference. Check these tests:

https://github.com/cristal-ise/cristal-ise/blob/develop/dsl/src/test/groovy/org/cristalise/dsl/test/persistency/outcome/SchemaBuilderReferenceSpecs.groovy

**Comment by kovax** [comment]
I see the code changes, you want to automatically check the uuid xsd type. Well, you can use `pattern` of xsd to acheive to same.
