### ISSUE TITLE
Add endpoint to download outcome attachments

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#341]
There should be a way to transparently store a file as an outcome attachment (this is already working) and later download that same file.

According to the spec ( see
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
and
https://tools.ietf.org/html/rfc2046#page-11)
a `text` mime type is supposed to be used only for human-readable non-binary data. The generic type for binary data is `application/octet-stream`.

Since the current `getScriptResult()` can only produce XML or JSON (see
https://github.com/cristal-ise/cristal-ise/blob/cb6f758668de1e1f54d339da6dbd29a260c874e0/restapi/src/main/java/org/cristalise/restapi/ItemRoot.java#L202), we need a new endpoint that can produce `application/octet-stream`.

**Comment by kovax** [comment]
Is it possible that a script will returns a binary stream as the result of its computation? 

On the other hand there is an endpoint is under development:
[ItemOutcomeAttachment.getBinaryData()](https://github.com/cristal-ise/cristal-ise/blob/feature/Issue323_RestapiReturnAttachment/restapi/src/main/java/org/cristalise/restapi/ItemOutcomeAttachment.java#L89)
