### ISSUE TITLE
Server-side scripting

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#344]
Currently `AgentProxy.execute(Job)` executes an activity's script on the client side (in restapi process), without any cristal transaction. Each `requestAction` goes through CORBA to the server side and runs in its own little transaction.
If any `requestAction` fails, the rollback of the previous `requestAction`s has to be implemented in the client-side script.

The activity's script should run inside an atomic transaction. This will simplify scripts: no need for rollback code.

**Proposed solution:**
`AgentProxy.execute(Job)`
```
if (Gateway.getProperties().getBoolean("ServerSideScripting", false)) {
    AgentProxy.executeLocal(Job);
}
```

`AgentProxy.executeLocal(Job)`
- call `item.requestActionWithScript()`

`Entity.idl`
- add `requestActionWithScript()`
- uncomment in `pom.xml` (or use a profile) and run `generate-sources`

`ItemProxy.requestActionWithScript()`
- call `ItemImplementation.requestActionWithScript()`

`ItemImplementation.requestActionWithScript()`
(another implementation of the `delegatedAction` method)
- start transaction
- run code from `AgentProxy.callScript()` with locker (need to create new Job object)
- call `lifecycle.requestAction()`
- commit/rollback transaction

`ItemProxy`
- Subscriptions should be switched off in ItemProxy on the server side (not on client side!), caching is done in ClusterStorageManager.
- Check the flow of ProxyManager notify and processMessage (). 

`Testing`
- Cristal-ise testing

**Comment by genetorres** [comment]
Testing result: Activity execution that calls another execute job inside script

Sets the locker in the requestActionWithScript()

![image](https://user-images.githubusercontent.com/41881351/76913951-7f482e80-68f3-11ea-81aa-b7a4a8ba9e3c.png)

Transaction being used when execute job was on called on the script

![image](https://user-images.githubusercontent.com/41881351/76914014-c0d8d980-68f3-11ea-8424-c354b2409cfc.png)

**Comment by genetorres** [comment]
Test Result:  Update Activity that would call another activity inside the script (server side)
![image](https://user-images.githubusercontent.com/41881351/78202161-23ba9b00-74c6-11ea-8b0b-18662a0e3b94.png)

**Comment by genetorres** [comment]
![image](https://user-images.githubusercontent.com/41881351/78203288-2f5b9100-74c9-11ea-8722-ca5ec201167d.png)

**Comment by kovax** [comment]
This work has become obsolete, as many intermediate steps were implemented to make the final implementation easier.
