### ISSUE TITLE
In the login process, use the default charset of running application when decoding base64 encoded password and username

### ISSUE THREAD

**Issue by patrickclercicube** [cristal-ise/cristal-ise#367]
When the user login the username and password are passed as base64 encoded string. 
The java.util.Base64 library hardcoded the decoding to StandardCharsets.ISO_8859_1.

But using the charset UTF-8 in the main application leads to some special character not decoded correctly from ISO_8859_1 to UTF-8.

The correction must be done in the org.cristalise.restapi.CookieLogin.java, method decode()
Current implementation:
```
private String decode(String encodedStr) {
        return new String(Base64.getDecoder().decode(encodedStr));
    }
```

Correction proposed: 
```
import java.nio.charset.Charset;

private String decode(String encodedStr) {
        return new String(Base64.getDecoder().decode(encodedStr.getBytes(Charset.defaultCharset())));
    }
```

**After more check the problem could come from the UI which send the username and password in ISO-8859-1 (as it seems to be a standard for base64 encoding). So the correct correction to be done is** 

```
return new String(Base64.getDecoder().decode(encodedStr), StandardCharsets.ISO_8859_1);
```

**Comment by kovax** [comment]
@patrickclercicube the current Bases64 `Decoder.decode(String)` useu the very same charset!?
