### ISSUE TITLE
Error validation of gui in deployed server

### ISSUE THREAD

**Issue by hyperion21** [cristal-ise/cristal-ise#451]

**Comment by hyperion21** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class de.mkammerer.argon2.jna.Argon2Library
        at de.mkammerer.argon2.Argon2i.callLibraryVerify(Argon2i.java:46)
        at de.mkammerer.argon2.BaseArgon2.verifyBytes(BaseArgon2.java:320)
        at de.mkammerer.argon2.BaseArgon2.verify(BaseArgon2.java:158)
        at de.mkammerer.argon2.BaseArgon2.verify(BaseArgon2.java:166)
```

**Comment by kovax** [comment]
@taurus227 and @hyperion21 
Please provide explanation why this issue needs to be fixed in the cristal-ise code, because all of my tests are working. Also as far as I know, this change is in use for some time on your system as well.

**Comment by taurus227** [comment]
@kovax You have updated the Argon2 version 2 months ago on 5.3.0:
https://github.com/cristal-ise/cristal-ise/blame/f375000cd1ec022c4255de53c6c5d147aa2b4908/jooqdb/pom.xml#L169
but we never switched to 5.3.0 (and that became some other version now).

We get the NoClassDefFoundError quoted above when we try to log in to the swingui.
