### ISSUE TITLE
Mask passwords when logging system properties

### ISSUE THREAD

**Issue by hyperion21** [cristal-ise/cristal-ise#455]
There's an INFO level log showing the database password in clear text, we should hide it:
```
16:38:40.230 [main] INFO  o.c.kernel.utils.ObjectProperties - JOOQ.password: (String):'******'
```

**Comment by kovax** [comment]
This is good point. This is already solved when the SystemPropertties are stored as an Outcome. Please check `ObjectProperties.convertToOutcome(...)` and use `ObjectProperties.propertiesToReduct()`.
