### ISSUE TITLE
Copy UUID using contextual menu

### ISSUE THREAD

**Issue by debbabi** [cristal-ise/cristal-ise#60]
Several activities of the new version of Cristalise Dev requires UUIDs on the outcome.
It will be more easier for us, users, to copy-past UUID directly using the GUI. 
I suggest to add a contextual menu on the Item name (UUID) label to copy the UUID corresponding to it.

![screen shot 2016-03-22 at 17 18 11](https://cloud.githubusercontent.com/assets/522491/13959103/ed705d2e-f052-11e5-890d-85f358ee9d3a.png)

**Comment by kovax** [comment]
swingui is not emproved anymore
