### ISSUE TITLE
kernel: Improve RemoteMap getLastId() method

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#84]
Currently the RemoteMap (used in History and JobList) loads all its keys by scanning its Cluster content to compute the last id. This could have huge impact  on performance for Item with long history. The complete scanning can be avoided by storing the last key in the Cluster. The original loadKeys() solution has to be kept for in-memory ClusterStorage implementation.

**Comment by taurus227** [comment]
Additional details:
- RemoteMap uses ClusterStorage, so it's database-agnostic
- We could store the lastEventId of each item in the Item table (should work, because currently only one thread can update an item at any given time: the `synchronized` is in the ItemImplementation)

**Comment by kovax** [comment]
The chosen solution  was to implement a ClusterStorage.getLastIntegerId() method which uses backend specific query to retireve the last id. This was no database change was required.
