### ISSUE TITLE
kernel: Script result is not returned when the single String output has a name

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#92]
If a script has a single String output defined, the resulting value is only returned if the output has no name. If the output has a name, the returned value is an empty String.

https://github.com/cristal-ise/kernel/blob/develop/src/main/java/org/cristalise/kernel/scripting/Script.java#L684
```
684:        if (mOutputParams.size() == 1) {
...
689:            if (StringUtils.isBlank(outputName)) {
...
695:            else {
                Object output = context.getBindings(ScriptContext.ENGINE_SCOPE).get(outputParam.getName());

                if (output == null) {
```
Maybe if there is a single output, we should not check if the name matches.

**Comment by kovax** [comment]
This was fixed already, but I cannot identify the issue number
