### ISSUE TITLE
Replace Logger with SLF4J logging framework

### ISSUE THREAD

**Issue by abranson** [cristal-ise/cristal-ise#99]
The internal logging system should be able to push its log messages to the standard java log framework.

**Comment by kovax** [comment]
- [ ] Make `org.cristalise.kernel.utilsLogger` deprecated. 
  Keep the class for dependent projects and Scripts to use it.
- [ ] replace all occurrence of `org.cristalise.kernel.utilsLogger` using Lombok @SLF4J
  - [ ] kernel
  - [ ] jooqdb
  - [ ] restapi
  - [ ] xpath-outcome-initiator
  - [ ] dsl
  - [ ] dev
  - [ ] testing
  - [ ] trigger
  - [ ] in-memory-lookup
  - [ ] gui
  - [ ] js-rhino
  - [ ] lookup-ldap
  - [ ] module-archetype
  - [ ] service
  - [ ] xmldb

**Comment by kovax** [comment]
Perhaps the better cheoice would be to use Google's Fluent Logger:
https://google.github.io/flogger/
